title: Johnathan Sun
description: >
  Student interested in philosophy, economics, and global development.
url: "https://jsun.one"
paginate:	2 # The number of posts to show per page on your homepage
name: "Johnathan"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
